### ISSUE TITLE
UnboundLocalError: validators 

### ISSUE THREAD

**Issue by MuNaught** [gerrymandr/RunDMCMC#161] opened 2018-07-12 16:09 UTC
Moved from previous thread. After pulling the latest version I'm getting an UnboundLocalError for the 'validators' variable: 
![validators_error](https://user-images.githubusercontent.com/9301226/42643880-35e6fc7c-85c8-11e8-8d00-5d141df10835.PNG)

Here's the config file used: 
[GRAPH_SOURCE]
gsource = C:/Users/pgirardet/Miniconda2/envs/vrdi/projects/yourstate/govt_VTDs/final_merged_shapefile.shp

[GRAPH_DATA]
id = ID
pop = POPULATION
cd = DISTRICT
area = tot_st_hou

[VALIDITY]
colrefuse_new_splits,10 = refuse_new_splits,10

[EVALUATION_SCORES]
col0 = efficiency_gap,dem_st_hou,rep_st_hou

[EVALUATION_SCORES_LOG]
colwrite_hists = write_hists

[SAVEFILENAME]
write_hists = hist.png
write_flips = json filename.json
write_p_values = report filename.txt

[MARKOV_CHAIN]
num_steps = 1000000
proposal = propose_random_flip
accept = always_accept

**Comment by MuNaught** [comment] 2018-07-12 18:00
I don't think I'm getting this issue at the moment. Will close for now and re-open if it comes up again.

**Comment by rwbogl** [comment] 2018-07-12 18:09
I'm not convinced that the issue is fixed. I think that if the `VALIDITY` section is not present (i.e., you chose no constraints), then this should occur. See around [this line in `parse_config.py`](https://github.com/gerrymandr/RunDMCMC/blob/b161d5c3a9df605fa7fe7d6c9586095c9d44365e/rundmcmc/parse_config.py#L247).

**Comment by rwbogl** [comment] 2018-07-12 20:20
Closed by #169. Reopen if there are any issues!

**Closed by rwbogl** 2018-07-12 20:20 UTC
Labels: bug
